### ISSUE TITLE
Introduce rustfmt to the project

### ISSUE THREAD

**Issue by djugei** [pdeljanov/Symphonia#4]
[rustmt](https://github.com/rust-lang/rustfmt) makes sure a consistent code style is used, lowering the barrier to contributing and ensuring uniformity.

**Comment by thomcc** [comment]
If it's intentionally not being used, another option is adding a rustfmt.toml file that ignores all files:

```toml
# put in rustfmt.toml at the project root.
ignore = ["/"]
```

That would at least help people out who have rustfmt configured to run by default, and also sorta serves as documentation of the decision not to use it.

**Comment by pdeljanov** [comment]
It's not intentional, but `rustfmt` doesn't always optimally format everything.

I have a `rustfmt.toml` locally (see below), but I'd like to avoid reformatting the big tables in the project since they're nicely aligned. Likewise, some vertically aligned code really aids in readability and `rustfmt` tends to mangle that.

So basically, need those tables excluded, and then a sanity check over the rest of the code to make sure `rustfmt` isn't mangling the format too badly. So it's been a low priority.

---

```toml
# rustfmt.toml
unstable_features = true
max_width = 100
array_width = 80
hard_tabs = false
tab_spaces = 4
newline_style = "Unix"
control_brace_style = "ClosingNextLine"
```
